category:
  name:
    - String berry
    - Mysmaily bakery
    - Nothing change
    - Coffee Cake
    - Loving Cake
  name_vn:
    - Chuỗi dâu tây
    - Hoàng Bánh
    - Không gì thay đổi
    - Bánh cà phê
    - Bánh tình yêu
    - Loving Cake